#!/bin/bash
echo "Helping..."
echo ""
echo ""

echo "📚 Claude Code PM - Project Management System"
echo "============================================="
echo ""
echo "🎯 Quick Start Workflow"
echo "  1. /pm:prd-new <name>        - Create a new PRD"
echo "  2. /pm:prd-parse <name>      - Convert PRD to epic"
echo "  3. /pm:epic-decompose <name> - Break into tasks"
echo "  4. /pm:epic-sync <name>      - Push to GitHub"
echo "  5. /pm:epic-start <name>     - Start parallel execution"
echo ""
echo "📄 PRD Commands"
echo "  /pm:prd-new <name>     - Launch brainstorming for new product requirement"
echo "  /pm:prd-parse <name>   - Convert PRD to implementation epic"
echo "  /pm:prd-list           - List all PRDs"
echo "  /pm:prd-edit <name>    - Edit existing PRD"
echo "  /pm:prd-status         - Show PRD implementation status"
echo ""
echo "📚 Epic Commands"
echo "  /pm:epic-decompose <name> - Break epic into task files"
echo "  /pm:epic-summary <name>   - Generate comprehensive epic summary"
echo "  /pm:epic-oneshot <name>   - Decompose and sync in one command"
echo "  /pm:epic-list             - List all epics"
echo "  /pm:epic-show <name>      - Display epic and its tasks"
echo "  /pm:epic-status [name]    - Show epic progress"
echo "  /pm:epic-close <name>     - Mark epic as complete"
echo "  /pm:epic-edit <name>      - Edit epic details"
echo "  /pm:epic-refresh <name>   - Update epic progress from tasks"
echo "  /pm:epic-start <name>     - Launch parallel agent execution"
echo ""
echo "📝 Task Commands"
echo "  /pm:task-show <num>       - Display task details and progress"
echo "  /pm:task-start <num>      - Begin work on task"
echo "  /pm:task-sync <num>       - Update task progress locally"
echo "  /pm:task-close <num>      - Mark task as complete"
echo "  /pm:task-reopen <num>     - Reopen closed task"
echo "  /pm:task-edit <num>       - Edit task details"
echo "  /pm:task-analyze <num>    - Analyze task for parallel work streams"
echo ""
echo "🔄 Workflow Commands"
echo "  /pm:next               - Show next priority tasks"
echo "  /pm:status             - Overall project dashboard"
echo "  /pm:standup            - Daily standup report"
echo "  /pm:blocked            - Show blocked tasks"
echo "  /pm:in-progress        - List work in progress"
echo ""
echo "📊 Reporting Commands"
echo "  /pm:epic-summary <name> - Generate detailed epic report"
echo ""
echo "🔧 Maintenance Commands"
echo "  /pm:validate           - Check system integrity"
echo "  /pm:clean              - Archive completed work"
echo "  /pm:search <query>     - Search across all content"
echo ""
echo "⚙️  Setup Commands"
echo "  /pm:init               - Initialize project management system"
echo "  /pm:help               - Show this help message"
echo ""
echo "💡 Tips"
echo "  • Use /pm:next to find available work"
echo "  • Run /pm:status for quick overview"
echo "  • Epic workflow: prd-new → prd-parse → epic-decompose → epic-summary"
echo "  • View README.md for complete documentation"

exit 0
